Add difficulty + Add timer
valkheim/KTNE-IRL pull request #4
Opened 2018-01-24 12:23 UTC by ChampiB

2018-01-24 12:37 UTC, valkheim requested changes

2018-01-24 12:37 UTC, valkheim commented on templates/master/master.ino
>  void HandleBombeExplosion()
remove useless function

2018-01-24 12:37 UTC, valkheim commented on templates/master/master.ino
> +    if ( myDataOut & (1<<i) ) {
Extra spaces

2018-01-24 12:37 UTC, valkheim commented on templates/master/master.ino
> +  uint8_t tab[10] = {119, 20, 179, 182, 212, 230, 231, 52, 247, 246};
A comment to explain that line may be fine

2018-01-26 15:23 UTC, 6e656d6d61 commented on ktne_core/ktne_core.cpp
> +void userMadeMistake(uint16_t error)
`applyPenality` is maybe a clearer name

2018-02-19 09:47 UTC, valkheim requested changes

2018-02-19 09:47 UTC, valkheim commented on templates/master/master.ino
> +void shiftOut(int myDataPin, int myClockPin, byte myDataOut)
Take care of spaces please.
In the whole project, spaces are around operators but not around brackets

2018-02-19 09:47 UTC, valkheim commented on templates/master/master.ino
> +void shiftOut(int myDataPin, int myClockPin, byte myDataOut)
Code style should be consistent in the project. Take care of spaces in assignations and around/inner parenthesis

2018-02-19 09:47 UTC, valkheim commented on modules/simon/simon.ino
> +void computeButtonsActivation(int analogValue, int readValue[4])
shouldnt be readValue an array of 5 ints as declared in updateButtons function ?

2018-02-19 09:47 UTC, valkheim commented on modules/simon/simon.ino
> +void shiftOut(int myDataPin, int myClockPin, byte myDataOut)
Function also declared in master. Might it be good to move it to the ktne_core lib ?

2018-02-19 09:47 UTC, valkheim commented on modules/simon/simon.ino
> +# define TRUE 1
Isn't it already defined in standard lib ?

2018-02-19 09:47 UTC, valkheim commented on modules/simon/simon.ino
> +  buttons[0] = computeUpdateButton(buttons[0], readValue[0]);
A for-loop may be leaner

2018-02-19 09:47 UTC, valkheim commented on modules/simon/simon.ino
> +    if (seq_user[getSizeOfSequenceRequired() - 1 - i] != seq_test[i])
A protection or a comment beside the difficulty levels declaration is necessary to avoid crash

2018-02-19 09:47 UTC, valkheim commented on modules/simon/simon.ino
> +# define STATE_LOW 0
Why not making use of standard LOW/HIGH ?
Because of STATE_STILL_HIGH ? Would it be possible to define the two other from the standard one ?

2018-02-19 09:47 UTC, valkheim commented on modules/simon/simon.ino
> +      if (buttons[color - 1] == STATE_HIGH)
One should remember to never use pin 0 for a color.
LED_* is defined in ktne_core.h

2018-02-19 09:47 UTC, valkheim commented on modules/simon/simon.ino
> +int chechUserSeq()
should return a boolean + verify function name

2018-02-19 09:52 UTC, ChampiB commented on modules/simon/simon.ino
> +# define TRUE 1
In the standard library true is define as !false. But I need exactly 1 because I use it with : WAIT_USER_SEQ = 2

2018-02-19 09:54 UTC, ChampiB commented on modules/simon/simon.ino
> +  buttons[0] = computeUpdateButton(buttons[0], readValue[0]);
Done

2018-02-19 09:54 UTC, ChampiB commented on modules/simon/simon.ino
> +void computeButtonsActivation(int analogValue, int readValue[4])
Done

2018-02-19 09:59 UTC, ChampiB commented on modules/simon/simon.ino
> +# define STATE_LOW 0
Same as TRUE / FALSE

2018-02-19 10:03 UTC, ChampiB commented on modules/simon/simon.ino
> +int chechUserSeq()
Also "return WAIT_USER_SEQ;"

2018-02-19 10:06 UTC, valkheim commented on templates/master/master.ino
> +
Remove extra line

2018-02-19 10:09 UTC, ChampiB commented on modules/simon/simon.ino
> +      if (buttons[color - 1] == STATE_HIGH)
Done

2018-02-19 10:14 UTC, ChampiB commented on modules/simon/simon.ino
> +    if (seq_user[getSizeOfSequenceRequired() - 1 - i] != seq_test[i])
Done

2018-02-19 10:15 UTC, ChampiB commented on templates/master/master.ino
> +
Done

2018-02-19 10:54 UTC, valkheim requested changes

2018-02-19 10:54 UTC, valkheim commented on modules/simon/simon.ino
> +  uint8_t tab[5] = {0, 2, 4, 8, 16};
Why not using defines in the tab initialization ?

2018-02-19 11:06 UTC, ChampiB commented on modules/simon/simon.ino
> +void shiftOut(int myDataPin, int myClockPin, byte myDataOut)
Done

2018-02-19 11:29 UTC, valkheim requested changes

2018-02-19 11:29 UTC, valkheim commented on libraries/ktne_shared/README.md
> +# KTNE module core library
KTNE module shared library

2018-02-19 11:29 UTC, valkheim commented on libraries/ktne_shared/README.md
> +## Core function(s)
shared function(s)

2018-02-19 11:29 UTC, valkheim commented on libraries/ktne_shared/74HC595.h
> +#ifndef _74HC595_H_
should be shared.h

2018-02-19 11:29 UTC, valkheim commented on libraries/ktne_shared/74HC595.cpp
> +  for (i=7; i>=0; i--)
spaces around = and >=

2018-02-19 11:29 UTC, valkheim commented on libraries/ktne_shared/74HC595.cpp
> +    if ( myDataOut & (1<<i) )
remove spaces inner parenthesis

2018-02-19 11:29 UTC, valkheim commented on libraries/ktne_shared/74HC595.cpp
> +  int i=0;
space around assignation

2018-02-19 12:21 UTC, ChampiB commented on libraries/ktne_shared/README.md
> +# KTNE module core library
Done

2018-02-19 12:21 UTC, ChampiB commented on libraries/ktne_shared/README.md
> +## Core function(s)
Done

2018-02-19 12:22 UTC, ChampiB commented on libraries/ktne_shared/74HC595.h
> +#ifndef _74HC595_H_
Done

2018-02-19 12:22 UTC, ChampiB commented on libraries/ktne_shared/74HC595.cpp
> +  for (i=7; i>=0; i--)
Done

2018-02-19 12:22 UTC, ChampiB commented on libraries/ktne_shared/74HC595.cpp
> +    if ( myDataOut & (1<<i) )
Done

2018-02-19 12:23 UTC, ChampiB commented on libraries/ktne_shared/74HC595.cpp
> +  int i=0;
Done

2018-02-19 13:57 UTC, valkheim approved these changes

2018-02-19 14:02 UTC, merged