Add module : Big Button
valkheim/KTNE-IRL pull request #5
Opened 2018-02-19 15:12 UTC by ChampiB

2018-02-19 16:28 UTC, valkheim requested changes

2018-02-19 16:28 UTC, valkheim commented on modules/bigButton/bigButton.ino
> +/****************************************
Update module desc

2018-02-19 16:28 UTC, valkheim commented on modules/bigButton/bigButton.ino
> +  //delay(100);
remove useless line

2018-02-20 17:52 UTC, ChampiB commented on modules/bigButton/bigButton.ino
> +/****************************************
Done

2018-02-20 17:59 UTC, valkheim approved these changes

2018-02-20 17:59 UTC, merged